### ISSUE TITLE
Add supermaven-agent-version

### ISSUE THREAD

**Issue by rolandtritsch** [crazywolf132/supermaven.el#4]
There is always the risk that newer versions of the agent break this integration.

Let's add a variable, e.g. ...

```lisp
(setq supermaven-agent-version 26)
```

... to download and use a specific version of `sm-agent`.

That way we can always go back to the last version of `sm-agent` that worked, while we make the latest work.

If `supermaven-agent-version` is not set or `nil`, the latest version will be downloaded and used.

**Comment by rolandtritsch** [comment]
@crazywolf132 Thoughts?

**Comment by crazywolf132** [comment]
This sounds fine by me

**Comment by rolandtritsch** [comment]
This will be fixed with #8
